/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SongwritingBook {
    }
}
declare global {
    interface HTMLSongwritingBookElement extends Components.SongwritingBook, HTMLStencilElement {
    }
    var HTMLSongwritingBookElement: {
        prototype: HTMLSongwritingBookElement;
        new (): HTMLSongwritingBookElement;
    };
    interface HTMLElementTagNameMap {
        "songwriting-book": HTMLSongwritingBookElement;
    }
}
declare namespace LocalJSX {
    interface SongwritingBook {
    }
    interface IntrinsicElements {
        "songwriting-book": SongwritingBook;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "songwriting-book": LocalJSX.SongwritingBook & JSXBase.HTMLAttributes<HTMLSongwritingBookElement>;
        }
    }
}
